spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://thaivanlam373_db_user:noh9QqTXzA8vXw0z@user-data.ux0vecp.mongodb.net/?retryWrites=true&w=majority&appName=user-data
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: root
#    password: root
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create


server:
  port: 8082