spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  management:
    endpoints:
      web:
        exposure:
          include: "*"

server:
  port: 8083

app:
  message: "Hello order"