spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database: ${DATABASE}
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${DDL_AUTO}
    database-platform: ${DATABASE_PLATFORM}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL}

server:
  port: ${PORT}


