spring:
  application:
    name: configdemo
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

#build:
#  id: ${ID}
#  version: ${VERSION}
#  name: ${NAME}

management:
  endpoints:
    web:
      exposure:
        include: refresh

#build:
#  id: 10101
#  version: 1.2.3.4
#  name: "Application"
#  type: "Application Build"

#ID=9999;NAME=NEW_NAME;VERSION=3.3.3.3