

build:
  id: 101
  version: 1.2.3
  name: "Native Default-Default-Build"
  type: "Native Default Build"

management:
  endpoints:
    web:
      exposure:
        include: refresh

#build:
#  id: 10101
#  version: 1.2.3.4
#  name: "Application"
#  type: "Application Build"

#ID=9999;NAME=NEW_NAME;VERSION=3.3.3.3